/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.dynamic.data.mapping.uad.anonymizer;

import com.liferay.dynamic.data.mapping.model.DDMContent;
import com.liferay.dynamic.data.mapping.service.DDMContentLocalService;
import com.liferay.dynamic.data.mapping.uad.constants.DDMUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the ddm content UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link DDMContentUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseDDMContentUADAnonymizer
	extends DynamicQueryUADAnonymizer<DDMContent> {

	@Override
	public void autoAnonymize(
			DDMContent ddmContent, long userId, User anonymousUser)
		throws PortalException {

		if (ddmContent.getUserId() == userId) {
			ddmContent.setUserId(anonymousUser.getUserId());
			ddmContent.setUserName(anonymousUser.getFullName());
		}

		ddmContentLocalService.updateDDMContent(ddmContent);
	}

	@Override
	public void delete(DDMContent ddmContent) throws PortalException {
		ddmContentLocalService.deleteContent(ddmContent);
	}

	@Override
	public Class<DDMContent> getTypeClass() {
		return DDMContent.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return ddmContentLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return DDMUADConstants.USER_ID_FIELD_NAMES_DDM_CONTENT;
	}

	@Reference
	protected DDMContentLocalService ddmContentLocalService;

}